// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz9tCAbjHuWAlQeqanWvzLYeGF412QwoU',
    appId: '1:930309965801:web:a20745c16ae9fd2fffad78',
    messagingSenderId: '930309965801',
    projectId: 'dailypulse-82f54',
    authDomain: 'dailypulse-82f54.firebaseapp.com',
    storageBucket: 'dailypulse-82f54.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz9tCAbjHuWAlQeqanWvzLYeGF412QwoU',
    appId: '1:930309965801:android:PLACEHOLDER',
    messagingSenderId: '930309965801',
    projectId: 'dailypulse-82f54',
    storageBucket: 'dailypulse-82f54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz9tCAbjHuWAlQeqanWvzLYeGF412QwoU',
    appId: '1:930309965801:ios:PLACEHOLDER',
    messagingSenderId: '930309965801',
    projectId: 'dailypulse-82f54',
    storageBucket: 'dailypulse-82f54.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz9tCAbjHuWAlQeqanWvzLYeGF412QwoU',
    appId: '1:930309965801:ios:PLACEHOLDER',
    messagingSenderId: '930309965801',
    projectId: 'dailypulse-82f54',
    storageBucket: 'dailypulse-82f54.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz9tCAbjHuWAlQeqanWvzLYeGF412QwoU',
    appId: '1:930309965801:web:a20745c16ae9fd2fffad78',
    messagingSenderId: '930309965801',
    projectId: 'dailypulse-82f54',
    authDomain: 'dailypulse-82f54.firebaseapp.com',
    storageBucket: 'dailypulse-82f54.firebasestorage.app',
  );
}
